server:
  port: 10008

spring:
  application:
    name: seata-order-micro-service-10008
  cloud:
    alibaba:
      seata:
        # 指定事务组名称,需要和seata server中的对应
        tx-service-group: ls_order_tx_group
    nacos:
      discovery:
        # 指定Nacos地址
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_micro_service?useInformationSchema=false
    username: root
    password: 88888888
# 配置seata 日志输出
logging:
  level:
    io:
      seata: info
    springcloud:
      dao: debug


mybatis:
  mapper-locations: classpath:mapper/*.xml