server:
  port: 80
# 配置Spring
spring:
  application:
    name: member-service-consumer-80 #配置应用名称
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
# 配置Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka9002.com:9002/eureka/,http://eureka9001.com:9001/eureka/
#      instance:
#        # 设置客户端向服务端EurekaServer 发送心跳的时间间隔  1秒 默认30s
#        lease-renewal-interval-in-seconds: 1
#        # 服务端收到最后一次心跳后等待时间上限 单位是秒 默认90s
#        lease-expiration-duration-in-seconds: 2



