server:
  port: 10000
# 配置Spring
spring:
  application:
    name: MEMBER-SERVICE-PROVIDER #配置应用名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/e_commerce_center_db?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 88888888
    # 配置Sleuth 和ZipKin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1  # 采样率 在0 - 1 之间  1: 全部采集  0:
# 配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml   # 指定mapper.xml文件位置
  type-aliases-package: springcloud.entity   # 设置类型别名的包 （实体类所在的包）


# 配置Eureka Client
eureka:
  client:
    register-with-eureka: true  # 表示将自己注册到Eureka Server
    fetch-registry: true        # 表示从Eureka Server 抓取注册信息,如果是单节点,可以不配置，但是如果是集群，则必须配置true才能配合Ribbon 使用负载均衡
    service-url:
      # 表示自己注册到哪个EurekaServer
      # 将本服务注册到多个Server 使用逗号间隔
      defaultZone: http://eureka9002.com:9002/eureka/,http://eureka9001.com:9001/eureka/
#  instance:
#    # 设置客户端向服务端EurekaServer 发送心跳的时间间隔  1秒
#    lease-renewal-interval-in-seconds: 1
#      # 服务端收到最后一次心跳后等待时间上限 单位是秒 默认90s
#    lease-expiration-duration-in-seconds: 2






